app/src/Entity/BrewMashing.php
<?php

namespace App\Entity;

use App\Repository\BrewMashingRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BrewMashingRepository::class)]
class BrewMashing
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\OneToOne(inversedBy: 'duration', cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false)]
    private ?Brew $brew_id = null;

    #[ORM\Column]
    private ?int $duration = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $details = null;

    /**
     * @var Collection<int, BrewMashingGrain>
     */
    #[ORM\OneToMany(targetEntity: BrewMashingGrain::class, mappedBy: 'mashing_id')]
    private Collection $grains;

    #[ORM\Column]
    private ?float $water = null;

    #[ORM\Column(nullable: true)]
    private ?float $water_rinsing = null;

    public function __construct()
    {
        $this->grains = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBrewId(): ?Brew
    {
        return $this->brew_id;
    }

    public function setBrewId(Brew $brew_id): static
    {
        $this->brew_id = $brew_id;

        return $this;
    }

    public function getDuration(): ?int
    {
        return $this->duration;
    }

    public function setDuration(int $duration): static
    {
        $this->duration = $duration;

        return $this;
    }

    public function getDetails(): ?string
    {
        return $this->details;
    }

    public function setDetails(string $details): static
    {
        $this->details = $details;

        return $this;
    }

    /**
     * @return Collection<int, BrewMashingGrain>
     */
    public function getGrains(): Collection
    {
        return $this->grains;
    }

    public function addGrain(BrewMashingGrain $grain): static
    {
        if (!$this->grains->contains($grain)) {
            $this->grains->add($grain);
            $grain->setMashingId($this);
        }

        return $this;
    }

    public function removeGrain(BrewMashingGrain $grain): static
    {
        if ($this->grains->removeElement($grain)) {
            // set the owning side to null (unless already changed)
            if ($grain->getMashingId() === $this) {
                $grain->setMashingId(null);
            }
        }

        return $this;
    }

    public function getWater(): ?float
    {
        return $this->water;
    }

    public function setWater(float $water): static
    {
        $this->water = $water;

        return $this;
    }

    public function getWaterRinsing(): ?float
    {
        return $this->water_rinsing;
    }

    public function setWaterRinsing(?float $water_rinsing): static
    {
        $this->water_rinsing = $water_rinsing;

        return $this;
    }
}

app/src/Form/BrewMashingType.php
<?php

namespace App\Form;

use App\Entity\Brew;
use App\Entity\BrewMashing;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BrewMashingType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('duration')
            ->add('details')
            ->add('water')
            ->add('water_rinsing')
            ->add('brew_id', EntityType::class, [
                'class' => Brew::class,
                'choice_label' => 'id',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => BrewMashing::class,
        ]);
    }
}

app/src/Controller/BrewMashingController.php
<?php

namespace App\Controller;

use App\Entity\BrewMashing;
use App\Form\BrewMashingType;
use App\Repository\BrewMashingRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/brew/mashing')]
final class BrewMashingController extends AbstractController
{
    #[Route(name: 'app_brew_mashing_index', methods: ['GET'])]
    public function index(BrewMashingRepository $brewMashingRepository): Response
    {
        return $this->render('brew_mashing/index.html.twig', [
            'brew_mashings' => $brewMashingRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_brew_mashing_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $brewMashing = new BrewMashing();
        $form = $this->createForm(BrewMashingType::class, $brewMashing);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($brewMashing);
            $entityManager->flush();

            return $this->redirectToRoute('app_brew_mashing_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('brew_mashing/new.html.twig', [
            'brew_mashing' => $brewMashing,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_brew_mashing_show', methods: ['GET'])]
    public function show(BrewMashing $brewMashing): Response
    {
        return $this->render('brew_mashing/show.html.twig', [
            'brew_mashing' => $brewMashing,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_brew_mashing_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, BrewMashing $brewMashing, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(BrewMashingType::class, $brewMashing);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_brew_mashing_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('brew_mashing/edit.html.twig', [
            'brew_mashing' => $brewMashing,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_brew_mashing_delete', methods: ['POST'])]
    public function delete(Request $request, BrewMashing $brewMashing, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$brewMashing->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($brewMashing);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_brew_mashing_index', [], Response::HTTP_SEE_OTHER);
    }
}

app/templates/brew_mashing/_delete_form.html.twig
<form method="post" action="{{ path('app_brew_mashing_delete', {'id': brew_mashing.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ brew_mashing.id) }}">
    <button class="btn">Delete</button>
</form>

app/templates/brew_mashing/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

app/templates/brew_mashing/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit BrewMashing{% endblock %}

{% block body %}
    <h1>Edit BrewMashing</h1>

    {{ include('brew_mashing/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_brew_mashing_index') }}">back to list</a>

    {{ include('brew_mashing/_delete_form.html.twig') }}
{% endblock %}

app/templates/brew_mashing/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}BrewMashing index{% endblock %}

{% block body %}
    <h1>BrewMashing index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Duration</th>
                <th>Details</th>
                <th>Water</th>
                <th>Water_rinsing</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for brew_mashing in brew_mashings %}
            <tr>
                <td>{{ brew_mashing.id }}</td>
                <td>{{ brew_mashing.duration }}</td>
                <td>{{ brew_mashing.details }}</td>
                <td>{{ brew_mashing.water }}</td>
                <td>{{ brew_mashing.waterRinsing }}</td>
                <td>
                    <a href="{{ path('app_brew_mashing_show', {'id': brew_mashing.id}) }}">show</a>
                    <a href="{{ path('app_brew_mashing_edit', {'id': brew_mashing.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_brew_mashing_new') }}">Create new</a>
{% endblock %}

app/templates/brew_mashing/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New BrewMashing{% endblock %}

{% block body %}
    <h1>Create new BrewMashing</h1>

    {{ include('brew_mashing/_form.html.twig') }}

    <a href="{{ path('app_brew_mashing_index') }}">back to list</a>
{% endblock %}

app/templates/brew_mashing/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}BrewMashing{% endblock %}

{% block body %}
    <h1>BrewMashing</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ brew_mashing.id }}</td>
            </tr>
            <tr>
                <th>Duration</th>
                <td>{{ brew_mashing.duration }}</td>
            </tr>
            <tr>
                <th>Details</th>
                <td>{{ brew_mashing.details }}</td>
            </tr>
            <tr>
                <th>Water</th>
                <td>{{ brew_mashing.water }}</td>
            </tr>
            <tr>
                <th>Water_rinsing</th>
                <td>{{ brew_mashing.waterRinsing }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_brew_mashing_index') }}">back to list</a>

    <a href="{{ path('app_brew_mashing_edit', {'id': brew_mashing.id}) }}">edit</a>

    {{ include('brew_mashing/_delete_form.html.twig') }}
{% endblock %}