app/src/Entity/GrainStock.php
<?php

namespace App\Entity;

use App\Repository\GrainStockRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: GrainStockRepository::class)]
class GrainStock
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $bought_at = null;

    #[ORM\Column]
    private ?float $weight = null;

    #[ORM\Column]
    private ?float $remaining_weight = null;

    #[ORM\ManyToOne(inversedBy: 'grainStocks')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Grain $grain_id = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBoughtAt(): ?\DateTimeImmutable
    {
        return $this->bought_at;
    }

    public function setBoughtAt(\DateTimeImmutable $bought_at): static
    {
        $this->bought_at = $bought_at;

        return $this;
    }

    public function getWeight(): ?float
    {
        return $this->weight;
    }

    public function setWeight(float $weight): static
    {
        $this->weight = $weight;

        return $this;
    }

    public function getRemainingWeight(): ?float
    {
        return $this->remaining_weight;
    }

    public function setRemainingWeight(float $remaining_weight): static
    {
        $this->remaining_weight = $remaining_weight;

        return $this;
    }

    public function getGrainId(): ?Grain
    {
        return $this->grain_id;
    }

    public function setGrainId(?Grain $grain_id): static
    {
        $this->grain_id = $grain_id;

        return $this;
    }
}

app/src/Form/GrainStockType.php
<?php

namespace App\Form;

use App\Entity\Grain;
use App\Entity\GrainStock;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class GrainStockType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('bought_at', null, [
                'widget' => 'single_text',
            ])
            ->add('weight')
            ->add('remaining_weight')
            ->add('grain_id', EntityType::class, [
                'class' => Grain::class,
                'choice_label' => 'id',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => GrainStock::class,
        ]);
    }
}

app/src/Controller/GrainStockController.php
<?php

namespace App\Controller;

use App\Entity\GrainStock;
use App\Form\GrainStockType;
use App\Repository\GrainStockRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/grain/stock')]
final class GrainStockController extends AbstractController
{
    #[Route(name: 'app_grain_stock_index', methods: ['GET'])]
    public function index(GrainStockRepository $grainStockRepository): Response
    {
        return $this->render('grain_stock/index.html.twig', [
            'grain_stocks' => $grainStockRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_grain_stock_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $grainStock = new GrainStock();
        $form = $this->createForm(GrainStockType::class, $grainStock);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($grainStock);
            $entityManager->flush();

            return $this->redirectToRoute('app_grain_stock_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('grain_stock/new.html.twig', [
            'grain_stock' => $grainStock,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_grain_stock_show', methods: ['GET'])]
    public function show(GrainStock $grainStock): Response
    {
        return $this->render('grain_stock/show.html.twig', [
            'grain_stock' => $grainStock,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_grain_stock_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, GrainStock $grainStock, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(GrainStockType::class, $grainStock);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_grain_stock_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('grain_stock/edit.html.twig', [
            'grain_stock' => $grainStock,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_grain_stock_delete', methods: ['POST'])]
    public function delete(Request $request, GrainStock $grainStock, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$grainStock->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($grainStock);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_grain_stock_index', [], Response::HTTP_SEE_OTHER);
    }
}

app/templates/grain_stock/_delete_form.html.twig
<form method="post" action="{{ path('app_grain_stock_delete', {'id': grain_stock.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ grain_stock.id) }}">
    <button class="btn">Delete</button>
</form>

app/templates/grain_stock/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

app/templates/grain_stock/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit GrainStock{% endblock %}

{% block body %}
    <h1>Edit GrainStock</h1>

    {{ include('grain_stock/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_grain_stock_index') }}">back to list</a>

    {{ include('grain_stock/_delete_form.html.twig') }}
{% endblock %}

app/templates/grain_stock/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}GrainStock index{% endblock %}

{% block body %}
    <h1>GrainStock index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Bought_at</th>
                <th>Weight</th>
                <th>Remaining_weight</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for grain_stock in grain_stocks %}
            <tr>
                <td>{{ grain_stock.id }}</td>
                <td>{{ grain_stock.boughtAt ? grain_stock.boughtAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ grain_stock.weight }}</td>
                <td>{{ grain_stock.remainingWeight }}</td>
                <td>
                    <a href="{{ path('app_grain_stock_show', {'id': grain_stock.id}) }}">show</a>
                    <a href="{{ path('app_grain_stock_edit', {'id': grain_stock.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_grain_stock_new') }}">Create new</a>
{% endblock %}

app/templates/grain_stock/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New GrainStock{% endblock %}

{% block body %}
    <h1>Create new GrainStock</h1>

    {{ include('grain_stock/_form.html.twig') }}

    <a href="{{ path('app_grain_stock_index') }}">back to list</a>
{% endblock %}

app/templates/grain_stock/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}GrainStock{% endblock %}

{% block body %}
    <h1>GrainStock</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ grain_stock.id }}</td>
            </tr>
            <tr>
                <th>Bought_at</th>
                <td>{{ grain_stock.boughtAt ? grain_stock.boughtAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Weight</th>
                <td>{{ grain_stock.weight }}</td>
            </tr>
            <tr>
                <th>Remaining_weight</th>
                <td>{{ grain_stock.remainingWeight }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_grain_stock_index') }}">back to list</a>

    <a href="{{ path('app_grain_stock_edit', {'id': grain_stock.id}) }}">edit</a>

    {{ include('grain_stock/_delete_form.html.twig') }}
{% endblock %}