app/src/Entity/BrewHopping.php
<?php

namespace App\Entity;

use App\Repository\BrewHoppingRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BrewHoppingRepository::class)]
class BrewHopping
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'hoppings')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Brew $brew_id = null;

    #[ORM\ManyToOne(inversedBy: 'bew_hoppings')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Hop $hop_id = null;

    #[ORM\Column]
    private ?int $weight = null;

    #[ORM\Column(length: 255)]
    private ?string $add_at = null;

    #[ORM\Column(nullable: true)]
    private ?int $sort = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBrewId(): ?Brew
    {
        return $this->brew_id;
    }

    public function setBrewId(?Brew $brew_id): static
    {
        $this->brew_id = $brew_id;

        return $this;
    }

    public function getHopId(): ?Hop
    {
        return $this->hop_id;
    }

    public function setHopId(?Hop $hop_id): static
    {
        $this->hop_id = $hop_id;

        return $this;
    }

    public function getWeight(): ?int
    {
        return $this->weight;
    }

    public function setWeight(int $weight): static
    {
        $this->weight = $weight;

        return $this;
    }

    public function getAddAt(): ?string
    {
        return $this->add_at;
    }

    public function setAddAt(string $add_at): static
    {
        $this->add_at = $add_at;

        return $this;
    }

    public function getSort(): ?int
    {
        return $this->sort;
    }

    public function setSort(?int $sort): static
    {
        $this->sort = $sort;

        return $this;
    }
}

app/src/Form/BrewHoppingType.php
<?php

namespace App\Form;

use App\Entity\Brew;
use App\Entity\BrewHopping;
use App\Entity\Hop;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BrewHoppingType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('weight')
            ->add('add_at')
            ->add('sort')
            ->add('brew_id', EntityType::class, [
                'class' => Brew::class,
                'choice_label' => 'id',
            ])
            ->add('hop_id', EntityType::class, [
                'class' => Hop::class,
                'choice_label' => 'id',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => BrewHopping::class,
        ]);
    }
}

app/src/Controller/BrewHoppingController.php
<?php

namespace App\Controller;

use App\Entity\BrewHopping;
use App\Form\BrewHoppingType;
use App\Repository\BrewHoppingRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/brew/hopping')]
final class BrewHoppingController extends AbstractController
{
    #[Route(name: 'app_brew_hopping_index', methods: ['GET'])]
    public function index(BrewHoppingRepository $brewHoppingRepository): Response
    {
        return $this->render('brew_hopping/index.html.twig', [
            'brew_hoppings' => $brewHoppingRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_brew_hopping_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $brewHopping = new BrewHopping();
        $form = $this->createForm(BrewHoppingType::class, $brewHopping);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($brewHopping);
            $entityManager->flush();

            return $this->redirectToRoute('app_brew_hopping_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('brew_hopping/new.html.twig', [
            'brew_hopping' => $brewHopping,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_brew_hopping_show', methods: ['GET'])]
    public function show(BrewHopping $brewHopping): Response
    {
        return $this->render('brew_hopping/show.html.twig', [
            'brew_hopping' => $brewHopping,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_brew_hopping_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, BrewHopping $brewHopping, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(BrewHoppingType::class, $brewHopping);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_brew_hopping_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('brew_hopping/edit.html.twig', [
            'brew_hopping' => $brewHopping,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_brew_hopping_delete', methods: ['POST'])]
    public function delete(Request $request, BrewHopping $brewHopping, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$brewHopping->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($brewHopping);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_brew_hopping_index', [], Response::HTTP_SEE_OTHER);
    }
}

app/templates/brew_hopping/_delete_form.html.twig
<form method="post" action="{{ path('app_brew_hopping_delete', {'id': brew_hopping.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ brew_hopping.id) }}">
    <button class="btn">Delete</button>
</form>

app/templates/brew_hopping/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

app/templates/brew_hopping/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit BrewHopping{% endblock %}

{% block body %}
    <h1>Edit BrewHopping</h1>

    {{ include('brew_hopping/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_brew_hopping_index') }}">back to list</a>

    {{ include('brew_hopping/_delete_form.html.twig') }}
{% endblock %}

app/templates/brew_hopping/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}BrewHopping index{% endblock %}

{% block body %}
    <h1>BrewHopping index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Weight</th>
                <th>Add_at</th>
                <th>Sort</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for brew_hopping in brew_hoppings %}
            <tr>
                <td>{{ brew_hopping.id }}</td>
                <td>{{ brew_hopping.weight }}</td>
                <td>{{ brew_hopping.addAt }}</td>
                <td>{{ brew_hopping.sort }}</td>
                <td>
                    <a href="{{ path('app_brew_hopping_show', {'id': brew_hopping.id}) }}">show</a>
                    <a href="{{ path('app_brew_hopping_edit', {'id': brew_hopping.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_brew_hopping_new') }}">Create new</a>
{% endblock %}

app/templates/brew_hopping/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New BrewHopping{% endblock %}

{% block body %}
    <h1>Create new BrewHopping</h1>

    {{ include('brew_hopping/_form.html.twig') }}

    <a href="{{ path('app_brew_hopping_index') }}">back to list</a>
{% endblock %}

app/templates/brew_hopping/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}BrewHopping{% endblock %}

{% block body %}
    <h1>BrewHopping</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ brew_hopping.id }}</td>
            </tr>
            <tr>
                <th>Weight</th>
                <td>{{ brew_hopping.weight }}</td>
            </tr>
            <tr>
                <th>Add_at</th>
                <td>{{ brew_hopping.addAt }}</td>
            </tr>
            <tr>
                <th>Sort</th>
                <td>{{ brew_hopping.sort }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_brew_hopping_index') }}">back to list</a>

    <a href="{{ path('app_brew_hopping_edit', {'id': brew_hopping.id}) }}">edit</a>

    {{ include('brew_hopping/_delete_form.html.twig') }}
{% endblock %}