app/src/Entity/Brew.php
<?php

namespace App\Entity;

use App\Repository\BrewRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BrewRepository::class)]
class Brew
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $updated_at = null;

    #[ORM\Column(length: 255)]
    private ?string $type = null;

    #[ORM\Column]
    private ?float $target_volume = null;

    #[ORM\Column(nullable: true)]
    private ?float $alcool = null;

    /**
     * @var Collection<int, BrewHistory>
     */
    #[ORM\OneToMany(targetEntity: BrewHistory::class, mappedBy: 'brew_id')]
    private Collection $histories;

    #[ORM\OneToOne(mappedBy: 'brew_id', cascade: ['persist', 'remove'])]
    private ?BrewMashing $mashing = null;

    #[ORM\OneToOne(mappedBy: 'brew_id', cascade: ['persist', 'remove'])]
    private ?BrewBoiling $boiling = null;

    /**
     * @var Collection<int, BrewHopping>
     */
    #[ORM\OneToMany(targetEntity: BrewHopping::class, mappedBy: 'brew_id')]
    private Collection $hoppings;

    #[ORM\OneToOne(mappedBy: 'brew_id', cascade: ['persist', 'remove'])]
    private ?BrewFermentation $fermentation = null;

    #[ORM\OneToOne(mappedBy: 'brew_id', cascade: ['persist', 'remove'])]
    private ?BrewBottling $bottling = null;

    #[ORM\Column(nullable: true)]
    private ?int $density_initial = null;

    #[ORM\Column(nullable: true)]
    private ?int $density_final = null;

    public function __construct()
    {
        $this->histories = new ArrayCollection();
        $this->hoppings = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): static
    {
        $this->id = $id;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getCreatedAt(): \DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): \DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeImmutable $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getType(): string
    {
        return $this->type;
    }

    public function setType(string $type): static
    {
        $this->type = $type;

        return $this;
    }

    public function getTargetVolume(): ?float
    {
        return $this->target_volume;
    }

    public function setTargetVolume(float $target_volume): static
    {
        $this->target_volume = $target_volume;

        return $this;
    }

    public function getAlcool(): ?float
    {
        return $this->alcool;
    }

    public function setAlcool(?float $alcool): static
    {
        $this->alcool = $alcool;

        return $this;
    }

    /**
     * @return Collection<int, BrewHistory>
     */
    public function getHistories(): Collection
    {
        return $this->histories;
    }

    public function addHistory(BrewHistory $history): static
    {
        if (!$this->histories->contains($history)) {
            $this->histories->add($history);
            $history->setBrewId($this);
        }

        return $this;
    }

    public function removeHistory(BrewHistory $history): static
    {
        if ($this->histories->removeElement($history)) {
            // set the owning side to null (unless already changed)
            if ($history->getBrewId() === $this) {
                $history->setBrewId(null);
            }
        }

        return $this;
    }

    public function getMashing(): ?BrewMashing
    {
        return $this->mashing;
    }

    public function setMashing(BrewMashing $mashing): static
    {
        // set the owning side of the relation if necessary
        if ($mashing->getBrewId() !== $this) {
            $mashing->setBrewId($this);
        }

        $this->mashing = $mashing;

        return $this;
    }

    public function getBoiling(): ?BrewBoiling
    {
        return $this->boiling;
    }

    public function setBoiling(BrewBoiling $boiling): static
    {
        // set the owning side of the relation if necessary
        if ($boiling->getBrewId() !== $this) {
            $boiling->setBrewId($this);
        }

        $this->boiling = $boiling;

        return $this;
    }

    /**
     * @return Collection<int, BrewHopping>
     */
    public function getHoppings(): Collection
    {
        return $this->hoppings;
    }

    public function addHopping(BrewHopping $hopping): static
    {
        if (!$this->hoppings->contains($hopping)) {
            $this->hoppings->add($hopping);
            $hopping->setBrewId($this);
        }

        return $this;
    }

    public function removeHopping(BrewHopping $hopping): static
    {
        if ($this->hoppings->removeElement($hopping)) {
            // set the owning side to null (unless already changed)
            if ($hopping->getBrewId() === $this) {
                $hopping->setBrewId(null);
            }
        }

        return $this;
    }

    public function getFermentation(): ?BrewFermentation
    {
        return $this->fermentation;
    }

    public function setFermentation(BrewFermentation $fermentation): static
    {
        // set the owning side of the relation if necessary
        if ($fermentation->getBrewId() !== $this) {
            $fermentation->setBrewId($this);
        }

        $this->fermentation = $fermentation;

        return $this;
    }

    public function getBottling(): ?BrewBottling
    {
        return $this->bottling;
    }

    public function setBottling(BrewBottling $bottling): static
    {
        // set the owning side of the relation if necessary
        if ($bottling->getBrewId() !== $this) {
            $bottling->setBrewId($this);
        }

        $this->bottling = $bottling;

        return $this;
    }

    public function getDensityInitial(): ?int
    {
        return $this->density_initial;
    }

    public function setDensityInitial(?int $density_initial): static
    {
        $this->density_initial = $density_initial;

        return $this;
    }

    public function getDensityFinal(): ?int
    {
        return $this->density_final;
    }

    public function setDensityFinal(?int $density_final): static
    {
        $this->density_final = $density_final;

        return $this;
    }
}

app/src/Form/BrewType.php
<?php

namespace App\Form;

use App\Entity\Brew;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Event\PostSubmitEvent;
use Symfony\Component\Form\Event\PreSubmitEvent;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BrewType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('type')
            ->add('save', SubmitType::class, ['label' => 'Brew'])
            ->addEventListener(FormEvents::PRE_SUBMIT, $this->setDefaults(...))
            ->addEventListener(FormEvents::POST_SUBMIT, $this->setTimestamps(...))
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Brew::class,
        ]);
    }
    public function setDefaults(PreSubmitEvent $event): void
    {
        $data = $event->getData();
        if (!$data['type']) {
            $data['type'] = $data['name'];
        }
        $event->setData($data);
    }

    public function setTimestamps(PostSubmitEvent $event): void
    {
        $data = $event->getData();
        $datetime = new \DateTimeImmutable();
        $data->setUpdatedAt($datetime);
        if (!$data->getId()) {
            $data->setCreatedAt($datetime);
        }
    }
}

app/src/Controller/BrewController.php
<?php

namespace App\Controller;

use App\Entity\Brew;
use App\Form\Brew1Type;
use App\Repository\BrewRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/brew')]
final class BrewController extends AbstractController
{
    #[Route(name: 'app_brew_index', methods: ['GET'])]
    public function index(BrewRepository $brewRepository): Response
    {
        return $this->render('brew/index.html.twig', [
            'brews' => $brewRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_brew_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $brew = new Brew();
        $form = $this->createForm(Brew1Type::class, $brew);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($brew);
            $entityManager->flush();

            return $this->redirectToRoute('app_brew_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('brew/new.html.twig', [
            'brew' => $brew,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_brew_show', methods: ['GET'])]
    public function show(Brew $brew): Response
    {
        return $this->render('brew/show.html.twig', [
            'brew' => $brew,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_brew_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Brew $brew, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(Brew1Type::class, $brew);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_brew_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('brew/edit.html.twig', [
            'brew' => $brew,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_brew_delete', methods: ['POST'])]
    public function delete(Request $request, Brew $brew, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$brew->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($brew);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_brew_index', [], Response::HTTP_SEE_OTHER);
    }
}

app/templates/brew/_delete_form.html.twig
<form method="post" action="{{ path('app_brew_delete', {'id': brew.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ brew.id) }}">
    <button class="btn">Delete</button>
</form>

app/templates/brew/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

app/templates/brew/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Brew{% endblock %}

{% block body %}
    <h1>Edit Brew</h1>

    {{ include('brew/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_brew_index') }}">back to list</a>

    {{ include('brew/_delete_form.html.twig') }}
{% endblock %}

app/templates/brew/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Brew index{% endblock %}

{% block body %}
    <h1>Brew index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Created_at</th>
                <th>Updated_at</th>
                <th>Type</th>
                <th>Target_volume</th>
                <th>Alcool</th>
                <th>Density_initial</th>
                <th>Density_final</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for brew in brews %}
            <tr>
                <td>{{ brew.id }}</td>
                <td>{{ brew.name }}</td>
                <td>{{ brew.createdAt ? brew.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ brew.updatedAt ? brew.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ brew.type }}</td>
                <td>{{ brew.targetVolume }}</td>
                <td>{{ brew.alcool }}</td>
                <td>{{ brew.densityInitial }}</td>
                <td>{{ brew.densityFinal }}</td>
                <td>
                    <a href="{{ path('app_brew_show', {'id': brew.id}) }}">show</a>
                    <a href="{{ path('app_brew_edit', {'id': brew.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_brew_new') }}">Create new</a>
{% endblock %}

app/templates/brew/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Brew{% endblock %}

{% block body %}
    <h1>Create new Brew</h1>

    {{ include('brew/_form.html.twig') }}

    <a href="{{ path('app_brew_index') }}">back to list</a>
{% endblock %}

app/templates/brew/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Brew{% endblock %}

{% block body %}
    <h1>Brew</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ brew.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ brew.name }}</td>
            </tr>
            <tr>
                <th>Created_at</th>
                <td>{{ brew.createdAt ? brew.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Updated_at</th>
                <td>{{ brew.updatedAt ? brew.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Type</th>
                <td>{{ brew.type }}</td>
            </tr>
            <tr>
                <th>Target_volume</th>
                <td>{{ brew.targetVolume }}</td>
            </tr>
            <tr>
                <th>Alcool</th>
                <td>{{ brew.alcool }}</td>
            </tr>
            <tr>
                <th>Density_initial</th>
                <td>{{ brew.densityInitial }}</td>
            </tr>
            <tr>
                <th>Density_final</th>
                <td>{{ brew.densityFinal }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_brew_index') }}">back to list</a>

    <a href="{{ path('app_brew_edit', {'id': brew.id}) }}">edit</a>

    {{ include('brew/_delete_form.html.twig') }}
{% endblock %}